export const strings = {
    LOCATION_DISALLOWED : 'But to serve you better, we really need to access your location. Please allow location permissions to utilize our services',
    PRICE_CHANGED : 'The prices of one or more products have changed since you last ordered them',
    QUANTITY_UNAVAILABLE : 'Some or more of the items are currently either out of stock or the quantities of one or more products are more than their present available stock',
    UNAVAILIBILITY : 'One or more products are currently unavailable. Available products have been added to your cart!',
    FEEDBACK_PLACEHOLDER : 'Your feedback about the dairy',
    DIFFERENT_SHOP_PRODUCTS : 'Your cart contains products from different  shops. Do you want discard previous items and add products from this dairy?',
    DELETE_ADDRESS_CONFIRMATION : 'Are you sure you want to delete this address?',
    COUPON_PLACEHOLDER : 'Search for a coupon or a referral code',
    PROBLEM_GETTING_PROFILE_DETAILS : 'Something went wrong while fetching your details. One or more details might be inaccurate',
    RECOVER_ACCOUNT_TEXT : 'Recover your account anytime and swiftly using an email id',
    SUBSCRIPTION_TEXT : `Please select your preferred subscription\nduration`,
    ENTER_OTP_TEXT : 'Please enter the OTP sent on your registered mobile number',
    PHONE_NUMBER_TEXT : 'Get all updates for your account on this number',
    AREA_NOT_SERVICEABLE : `We do not seem to be delivering to\nyour location yet.\nPlease wait while we find\nour way to you!`,
    SUBSCRIBABLE_ORDER : `You are seeing this area because\nyour cart contains items that are subscribable.\nIf you do not select the duration, the order shall\nfall back to a one-time order`,
    CONFIRM_PROFILE_DETAILS : "Please ensure that you have saved your details before leaving",
    DELIVERY_LOCATION_OUT_OF_RANGE : 'You are trying to use an address that is out of the delivery range of the shop. Please try another address or add items from a different shop',
    LOCATION_ERROR : 'We are having some problem fetching your location. Pease try after some time',
    SUBSRIBABLE_PRODUCT : 'The calendar indicates that this is a subscribable product',
    ORDER_ALREADY_RATED : 'This order has already been rated previosuly',
    SUBSCRIPTION_ORDER : 'You are seeing this section because this is a subscription order',
    CONFIRM_LOGOUT: 'Are you sure you want to logout?',
    MARK_NOTIFICATIONS_AS_READ: 'Mark all as read',
    DAIRY_IMAGES: "Some images from this dairy",
    PAYMENT_INITIATION_FAIL: "The payment could not be initiated",
    ITEMS_FROM_DIFFERENT_SHOP: `Your cart contains products from different  shops. Do you want to discard previous items and add products from this dairy?`,
    PAYMENT_UNSUCCESSFUL: "The transaction was not successful",
    TRANSACTION_FAILED: 'The transaction failed',
    NO_ORDERS: `Looks like you haven't\nplaced any orders yet.\nMake your menu now`,
    SUBSCRIPTION_PAUSE_START: "From when do you want to stop this subscription?",
    SUBSCRIPTION_PAUSE_END: "Till when do you want to stop this subscription?",
    CONFIRM_PAUSE_SUBSCRIPTION: "Are you sure you want to pause\nyour subscription?",
    ERROR_UPDATING_CART: "We are having trouble updating your cart. Details you see may or may not be accurate. Please try again in some time!",
    SHARE_COUPON_CODE: "Share your coupon code with your friends",
    ITEMS_REMOVED: `One or more products were removed by the dairy while you were away. We aplogoize for the inconvenience`,
    HELP_TITLE: "Get help for your order #",
    HELP_CATEGORY: "Select a category that best defines your grievance",
    HELP_CONTACT: "All communications shall be communicated on",
    NO_NOTIFICATIONS: "You seem to be all caught up over here!",

    PAYMENT_STATUS: {
        SUCCESS: "TXN_SUCCESS",
        FAILURE: "TXN_FAILURE",
        PENDING: "PENDING"
    }
}